  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  namespace: staging
  commonLabels:
    app: crud-staging-app1
    env: staging
  resources:
  - namespace.yaml
  - app-postgress-secrets-sealed.yaml
  - app-signal-secrets-sealed.yaml

  bases:
  - ../../base/
