apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app.fullname" . }}-svc
  labels:
    app: {{ .Values.appName }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appName }}