apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-app.fullname" . }}-config
  labels:
    app: {{ .Values.appName }}
data:
{{ tpl (.Files.Get "config/configmap.properties") . | nindent 2}}
