apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-app.fullname" . }}-config
  labels:
    app: {{ .Values.appName }}
data:
{{- toYaml .Values.configmap | nindent 2 }}
  SFX_SERVICE_NAME: {{ include "demo-app.fullname" . }}-svc
  JAEGER_SERVICE_NAME: {{ include "demo-app.fullname" . }}-svc