  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  namespace: staging
  commonLabels:
    app: crud-staging-app1
    env: staging
  images:
  - name: nginx:latest 
    newname: asia.gcr.io/hip-microservices-experiment-2/crud-demo-app@sha256
    newTag: 1d0d20effaf07fca9acbdf5b5d8330f2b917793ddfb72e9e81c3ae45d4bcf851

  bases:
  - ../app1/
