apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crud-app-demo-1-v1
spec:
  template:
    spec:
      containers:
      - name: crud-app-demo-1
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1024m"
          limits:
            memory: "2048Mi"
            cpu: "1024m"

