  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization  
  resources:
  - app-deployment.yaml
  - app-service.yaml
  configMapGenerator:
  - name: crud-app-demo-1-config
    literals:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.83.48.3:5432/postgres
      - SFX_SERVICE_NAME=crud-app-demo-1
      - JAEGER_SERVICE_NAME=crud-app-demo-1
      - JAEGER_PROPAGATION=b3

